name: Front React CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

defaults:
  run:
    working-directory: ./apps/front

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Download project from git
        uses: actions/checkout@v3

      - name: Build project
        run: |
          pnpm install
          pnpm run build

      - name: Testing project
        run: pnpm test

      - name: Create env file
        run: |
          touch .env
          cat .env

      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./dist
