name: Front React CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

defaults:
  run:
    working-directory: ./apps/web

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Download project from git
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo VITE_API_URL=${{ vars.API_URL }} >> .env

      - name: Build project
        run: |
          pnpm install
          pnpm run build

      - name: Testing project
        run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploying project in remote SSH
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
            cd kreative-club-app
            git fetch
            git pull 
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            pm2 restart kreative-club-web

# SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           ARGS: "-rlgoDzvc -i"
#           SOURCE: "web/"
#           REMOTE_HOST: ${{ secrets.HOST }}
#           REMOTE_USER: ${{ secrets.USERNAME }}
#           TARGET: ${{ secrets.TARGET }}
#           EXCLUDE: "/node_modules/"
#           SCRIPT_BEFORE: |
#             whoami
#             ls -al
#           SCRIPT_AFTER: |
#             whoami
#             ls -al
#             echo $RSYNC_STDOUT
#             npm install
