name: Front React CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

defaults:
  run:
    working-directory: ./apps/front

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Download project from git
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo VITE_API_URL=${{ vars.API_URL }} >> .env

      - name: Build project
        run: |
          pnpm install
          pnpm run build

      - name: Testing project
        run: pnpm test

      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./apps/web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: ./web

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "web/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/node_modules/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
